### ISSUE TITLE
Mainnet launch checklist

### ISSUE THREAD

**Issue by lastmjs** [lastmjs/demergence#5]
- [ ] Multiple security audits (2-3)
  - [ ] Trail of Bits?
  - [ ] Open Zeppelin?
- [ ] Property-based tests?
- [ ] Figure out initial distribution (do we transfer the tokens from Ropsten to the main net?)
